name: Build and Deploy
on:
  push:
    branches:
      - mytrails
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: build
    runs-on: ubuntu-latest
  yt:
    name: yt
    runs-on: ubuntu-latest
  